### ISSUE TITLE
Only first skill loaded from DB

### ISSUE THREAD

**Issue by loentar** [Darkin47/SagaRevised#10]
Upon character load only first skill loaded from DB, because of there are unexpected `return true` statement. 
It should be outside of `while` cycle.

This leads to only first skill is loaded and Novice's "Short sword mastery" is not available, because it is the second character's skill.

https://github.com/JulienGrv/saga-revised/blob/0a275bdcff56b80606728e5fcdeadc94a1c4bf26/Abstraction/Saga.Map.Data.Mysql/MysqlProvider.Characters.cs#L1153

**Comment by JulienGrv** [comment]
Hi loentar!
Thank you for your PR, I will review it on Sunday. I am still on holiday until there :)

**Comment by JulienGrv** [comment]
Fixed with PR #11
