### ISSUE TITLE
Error with quest 253

### ISSUE THREAD

**Issue by Daniel4rt** [Darkin47/SagaRevised#13]
Saga.Map give me this error of quest 253.
I read the code on Quests/253.xml and it's fine.
![image](https://user-images.githubusercontent.com/12065815/30561445-4fe71b3c-9c78-11e7-867f-cb53fc1b9371.png)

Saga.Map LOG:
![image](https://user-images.githubusercontent.com/12065815/30561509-82c8e292-9c78-11e7-854f-7e4c3cab294f.png)

When this error apear, can't login to the server.
![image](https://user-images.githubusercontent.com/12065815/30561543-9a2beeca-9c78-11e7-83ce-fa4cfefd7e6c.png)

**Comment by JulienGrv** [comment]
When does it happen? When you get the quest, during step 1 of the quest, when you just finish it,...?

**Comment by Daniel4rt** [comment]
I completed the first step of scenario quest, when I'm on hodemimes, has thrown this error.

**Comment by JulienGrv** [comment]
Ok it is the scenario quest. I don't know actually if the scenario quest are supported yet. I will try to see if I can fix the problem, if not I will deactivate the quest to avoid the bug.

**Comment by Daniel4rt** [comment]
Update:
This error happend to all quest when talk with the NPC without an order.

Example:
251 > 252 > 253

I talk 253 before 251, we need QUEST_VERIFY to check if the last step NPC is done.

**Comment by Daniel4rt** [comment]
![image](https://user-images.githubusercontent.com/12065815/30562115-96b94d6c-9c7a-11e7-8d9a-dfb20152c371.png)

**Comment by Daniel4rt** [comment]
Error is on:
https://github.com/JulienGrv/saga-revised/blob/master/Abstraction/Saga.Map.Data.LuaQuest/ScenarioLuaQuest.cs#L143

**Comment by Daniel4rt** [comment]
Temporary fix.
#14

**Comment by Daniel4rt** [comment]
Fix on Pull #15
