### ISSUE TITLE
Saga.Authentication error 

### ISSUE THREAD

**Issue by mikadoryu** [Darkin47/SagaRevised#3]
Saga.Authentication stopped working after turning off the pc

""
System.Net.Sockets.SocketException: Intento de acceso a un socket no permitido p
or sus permisos de acceso
   en System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress
socketAddress)
   en System.Net.Sockets.Socket.Bind(EndPoint localEP)
   en System.Net.Sockets.TcpListener.Start(Int32 backlog)
   en Saga.Shared.NetworkCore.Manager`1.Start() en c:\Users\Familia\Desktop\Saga
Revised- windows\Shared\Saga.Shared\Managers\Manager.cs:línea 30
   en Saga.Managers.NetworkService.OpenPublicNetworkConnections() en c:\Users\Fa
milia\Desktop\SagaRevised- windows\Saga.Authentication\Managers\Managers.Network
Service.cs:línea 101
""

**Comment by JulienGrv** [comment]
Can you print the error log? It's in the file Saga.Authentication.log.csv.

**Comment by JulienGrv** [comment]
Closed for inactivity.
