### ISSUE TITLE
I will continue to develop this project. Can you provide a translation tool software for the client?

### ISSUE THREAD

**Issue by WangShuXian6** [Darkin47/SagaRevised#35]
I will continue to develop this project. Can you provide a translation tool software for the client? 

I want to translate the client into Chinese, 

as there are over 30 Chinese players in my community.

 Here is our forum, https://github.com/WangShuXian6/RO2/discussions
which has just been established

我会继续开发这个项目，可以提供客户端的翻译工具软件吗？我想把客户端翻译为中文，我的社群里有30多名中国玩家。这里是我们的论坛，刚刚建成。
感谢大佬的工作！代码非常优秀！

**Comment by JulienGrv** [comment]
Hi @WangShuXian6 ,

there was a tool for translation back in the days. I don't know if I still have it somewhere but I will have a look and let you know.

I think this tool was an hex editor, maybe you will be able to use one to translate or make yourself one. 

I already wish you good luck in your endeavors!

**Comment by JulienGrv** [comment]
I found this repository: https://github.com/ELMASTERS/ro2trans

See also: https://code.google.com/archive/p/ro2trans/
