### ISSUE TITLE
GM bug

### ISSUE THREAD

**Issue by virkmx** [Darkin47/SagaRevised#4]
well i made my char with 255 GM lvl and it doesnt let me use GM commands it says commands fail 

i made it by console adding the GM lv and by sql table none of them works 

Thanks in advance =)

**Comment by JulienGrv** [comment]
Hi, thank you for your report!
I never tried a gm level above 99 so I don't know if it works. I suggest you use level 99 at most. I'll try to add numbers above 99 later when I have time to do so. I don't think it's a critical issue at the moment.
Darkin.

**Comment by JulienGrv** [comment]
We won't implement this feature. Please use 99 instead of 255.
