### ISSUE TITLE
Is it the latest version? Does it run under Linux?

### ISSUE THREAD

**Issue by omfgitsgoku** [Darkin47/SagaRevised#8]
I want to know if its the lastest rev for server and if its posible run on linux dedicated server?

**Comment by JulienGrv** [comment]
This emulator is based on the latest revision (rev. 4) of SIN (Stille in Norden), which was itself based on the latest revision (rev. 75) of SagaRevised. The changes added by the project SIN as well as in this repository are bug fixes as well as improvements of some of the base code.

It is theoretically possible to run the emulator under Linux using Mono. In practice, I don't know of someone who were able to do it.

**Comment by JulienGrv** [comment]
Instructions to run the emulator under Linux using Mono are now available. See PR #16.
